"""empty message

Revision ID: 73bc490b208b
Revises: 
Create Date: 2017-07-17 15:51:52.507045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc490b208b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_model',
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_model',
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('first_name')
    )
    op.create_table('perms',
    sa.Column('user_model.first_name', sa.Integer(), nullable=True),
    sa.Column('permission_model.name', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_model.name'], ['user_model.first_name'], ),
    sa.ForeignKeyConstraint(['user_model.first_name'], ['permission_model.name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perms')
    op.drop_table('user_model')
    op.drop_table('permission_model')
    # ### end Alembic commands ###
